INSERT INTO APP.ADMINISTRATOR (HASH, NAME, SUSPENDED) VALUES ('$2a$10$ywmZ4cSeOtGoQX/gijAW7uhy7MMttBxQW7e8Xvkhb97iL/4h9xwLS', 'Admin', 1);
INSERT INTO APP.ADMINISTRATOR (HASH, NAME, SUSPENDED) VALUES ('$2a$10$ywmZ4cSeOtGoQX/gijAW7uhy7MMttBxQW7e8Xvkhb97iL/4h9xwLS', 'Admin2', 0);

INSERT INTO APP.ADMINISTRATOR_PERMISSIONS (ADMINISTRATOR_ID, PERMISSIONS) VALUES (2, 1);

INSERT INTO APP.CURRICULAR (NAME) VALUES ('Aardrijkskunde');
INSERT INTO APP.CURRICULAR (NAME) VALUES ('Geschiedenis');
INSERT INTO APP.CURRICULAR (NAME) VALUES ('Sport');
INSERT INTO APP.CURRICULAR (NAME) VALUES ('Technologische opvoeding');

INSERT INTO APP.TARGETGROUP (NAME) VALUES ('Secundair');
INSERT INTO APP.TARGETGROUP (NAME) VALUES ('Kleuters');

INSERT INTO APP.FIRM (EMAIL, NAME, PHONENUMBER, WEBSITE) VALUES ('bedrijf@example.com', 'ProFarma', null, null);
INSERT INTO APP.FIRM (EMAIL, NAME, PHONENUMBER, WEBSITE) VALUES ('info@decathlon.com', 'Decathlon', '056735656', null);
INSERT INTO APP.FIRM (EMAIL, NAME, PHONENUMBER, WEBSITE) VALUES ('willaert@online.be', 'Verkleedkledij Willaert', '056713092', null);
INSERT INTO APP.FIRM (EMAIL, NAME, PHONENUMBER, WEBSITE) VALUES ('info@synhaeve.be', 'Doe-het-Zelf Synhaeve', '047665', null);
INSERT INTO APP.FIRM (EMAIL, NAME, PHONENUMBER, WEBSITE) VALUES ('dslkfj@kfdf.com', 'gg', '', null);

INSERT INTO APP.MATERIAL (ARTICLENR, DESCRIPTION, ENCODING, NAME, PRICE, FIRM_ID) VALUES ('456897', 'American Football Ball Bullet Black', 'jpg', 'American Football Ball', 6.95, null);
INSERT INTO APP.MATERIAL (ARTICLENR, DESCRIPTION, ENCODING, NAME, PRICE, FIRM_ID) VALUES ('465486', 'Roman Centurion Helmet Red top', 'jpg', 'Romeinse Helm', 95.00, null);
INSERT INTO APP.MATERIAL (ARTICLENR, DESCRIPTION, ENCODING, NAME, PRICE, FIRM_ID) VALUES ('SH372', 'Een zeer stevige hamer', 'jpg', 'Stanley hamer', 15.00, null);

INSERT INTO APP.MATERIAL_CURRICULAR (MATERIAL_ID, CURRICULAR_ID) VALUES (5, 3);
INSERT INTO APP.MATERIAL_CURRICULAR (MATERIAL_ID, CURRICULAR_ID) VALUES (6, 2);
INSERT INTO APP.MATERIAL_CURRICULAR (MATERIAL_ID, CURRICULAR_ID) VALUES (7, 3);
INSERT INTO APP.MATERIAL_CURRICULAR (MATERIAL_ID, CURRICULAR_ID) VALUES (7, 4);

INSERT INTO APP.MATERIAL_TARGETGROUP (MATERIAL_ID, TARGETGROUP_ID) VALUES (6, 1);
INSERT INTO APP.MATERIAL_TARGETGROUP (MATERIAL_ID, TARGETGROUP_ID) VALUES (7, 1);

INSERT INTO APP.MATERIALIDENTIFIER (PLACE, VISIBILITY, INFO_ID) VALUES ('B1.0123', 0, 5);
INSERT INTO APP.MATERIALIDENTIFIER (PLACE, VISIBILITY, INFO_ID) VALUES ('B1.0123', 1, 5);
INSERT INTO APP.MATERIALIDENTIFIER (PLACE, VISIBILITY, INFO_ID) VALUES ('Materiaalkot', 2, 5);
INSERT INTO APP.MATERIALIDENTIFIER (PLACE, VISIBILITY, INFO_ID) VALUES ('Materiaalkot', 2, 5);

INSERT INTO APP.RESERVATION (CREATIONDATE, ENDDATE, STARTDATE, USER_ID) VALUES ('2016-03-03', '2016-03-14', '2016-03-19', 1);
INSERT INTO APP.RESERVATION (CREATIONDATE, ENDDATE, STARTDATE, USER_ID) VALUES ('2016-02-09', '2016-03-07', '2016-03-12', 2);

INSERT INTO APP.RESERVATION_MATERIALIDENTIFIER (RESERVATION_ID, MATERIALIDENTIFIERSLIST_ID) VALUES (1, 6);
INSERT INTO APP.RESERVATION_MATERIALIDENTIFIER (RESERVATION_ID, MATERIALIDENTIFIERSLIST_ID) VALUES (1, 7);
INSERT INTO APP.RESERVATION_MATERIALIDENTIFIER (RESERVATION_ID, MATERIALIDENTIFIERSLIST_ID) VALUES (2, 8);

INSERT INTO APP."user"(EMAIL, FACULTY, FIRSTNAME, LASTNAME, TELNUMBER, TYPE) VALUES ('matthias.kunnen@gmail.com', 'FBO', 'Matthias', 'Kunnen', '+32474022497', 1);