INSERT INTO dbo.CURRICULAR (NAME) VALUES ('Aardrijkskunde');
INSERT INTO dbo.CURRICULAR (NAME) VALUES ('Geschiedenis');
INSERT INTO dbo.CURRICULAR (NAME) VALUES ('Sport');
INSERT INTO dbo.CURRICULAR (NAME) VALUES ('Technologische opvoeding');

INSERT INTO dbo.TARGETGROUP (NAME) VALUES ('Secundair');
INSERT INTO dbo.TARGETGROUP (NAME) VALUES ('Kleuters');

INSERT INTO dbo.FIRM (EMAIL, NAME, PHONENUMBER, WEBSITE) VALUES ('bedrijf@example.com', 'ProFarma', null, null);
INSERT INTO dbo.FIRM (EMAIL, NAME, PHONENUMBER, WEBSITE) VALUES ('info@decathlon.com', 'Decathlon', '056735656', null);
INSERT INTO dbo.FIRM (EMAIL, NAME, PHONENUMBER, WEBSITE) VALUES ('willaert@online.be', 'Verkleedkledij Willaert', '056713092', null);
INSERT INTO dbo.FIRM (EMAIL, NAME, PHONENUMBER, WEBSITE) VALUES ('info@synhaeve.be', 'Doe-het-Zelf Synhaeve', '047665', null);
INSERT INTO dbo.FIRM (EMAIL, NAME, PHONENUMBER, WEBSITE) VALUES ('dslkfj@kfdf.com', 'gg', null, null);

INSERT INTO dbo.MATERIAL (ARTICLENR, DESCRIPTION, ENCODING, NAME, PRICE, FIRMID) VALUES ('456897', 'American Football Ball Bullet Black', 'jpg', 'American Football Ball', 6.95, null);
INSERT INTO dbo.MATERIAL (ARTICLENR, DESCRIPTION, ENCODING, NAME, PRICE, FIRMID) VALUES ('465486', 'Roman Centurion Helmet Red top', 'jpg', 'Romeinse Helm', 95.00, null);
INSERT INTO dbo.MATERIAL (ARTICLENR, DESCRIPTION, ENCODING, NAME, PRICE, FIRMID) VALUES ('SH372', 'Een zeer stevige hamer', 'jpg', 'Stanley hamer', 15.00, null);

INSERT INTO dbo.MATERIALCURRICULAR (MATERIALID, CURRICULARID) VALUES (5, 3);
INSERT INTO dbo.MATERIALCURRICULAR (MATERIALID, CURRICULARID) VALUES (6, 2);
INSERT INTO dbo.MATERIALCURRICULAR (MATERIALID, CURRICULARID) VALUES (7, 3);
INSERT INTO dbo.MATERIALCURRICULAR (MATERIALID, CURRICULARID) VALUES (7, 4);

INSERT INTO dbo.MATERIALTARGETGROUP (MATERIALID, TARGETGROUPID) VALUES (6, 1);
INSERT INTO dbo.MATERIALTARGETGROUP (MATERIALID, TARGETGROUPID) VALUES (7, 1);

INSERT INTO dbo.MATERIALIDENTIFIER (PLACE, VISIBILITY, INFOID) VALUES ('B1.0123', 0, 5);
INSERT INTO dbo.MATERIALIDENTIFIER (PLACE, VISIBILITY, INFOID) VALUES ('B1.0123', 1, 5);
INSERT INTO dbo.MATERIALIDENTIFIER (PLACE, VISIBILITY, INFOID) VALUES ('Materiaalkot', 2, 5);
INSERT INTO dbo.MATERIALIDENTIFIER (PLACE, VISIBILITY, INFOID) VALUES ('Materiaalkot', 2, 5);

INSERT INTO dbo.RESERVATION (CREATIONDATE, ENDDATE, STARTDATE, USERID) VALUES ('2016-03-03', '2016-03-14', '2016-03-19', 1);
INSERT INTO dbo.RESERVATION (CREATIONDATE, ENDDATE, STARTDATE, USERID) VALUES ('2016-02-09', '2016-03-07', '2016-03-12', 2);

INSERT INTO dbo.ReservationDetail(RESERVATIONID, MATERIALIDENTIFIERID) VALUES (1, 6);
INSERT INTO dbo.ReservationDetail (RESERVATIONID, MATERIALIDENTIFIERID) VALUES (1, 7);
INSERT INTO dbo.ReservationDetail (RESERVATIONID, MATERIALIDENTIFIERID) VALUES (2, 8);

INSERT INTO dbo."user"(EMAIL, FACULTY, FIRSTNAME, LASTNAME, TELNUMBER, TYPE) VALUES ('matthias.kunnen@gmail.com', 'FBO', 'Matthias', 'Kunnen', '+32474022497', 1);